[workspace]
members = ["auto-login", "counter", "echo", "echo-tell", "file-logger", "hello-world", "keyboard-logger", "movement-demo", "position-tracker", "spell-caster", "trade-acceptor", "xtask"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Bryce Mecum <petridish@gmail.com>"]
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
gromnie-scripting-api = { git = "https://github.com/amoeba/gromnie", default-features = false }
